[package]
name = "back"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
thiserror = "1.0.59"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hyper = "*"
sqlx = { version = "=0.8.1", features = ["sqlite"] }
rusqlite = "=0.32.1"
