[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@openzeppelin=./lib/openzeppelin-contracts/contracts"]
solc-version = "0.8.25"

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
